### ISSUE TITLE
能否增加，当点击时不再是第一项

### ISSUE THREAD

**Issue by yang10560** [ChatGPTBox-dev/chatGPTBox#355]
**Describe the solution you'd like**
当鼠标点击时，触发的不是第一项option ” CHATGPT(网页版）” 而是由用户设置定的默认值

**Comment by josStorer** [comment]
设置里可以改

![image](https://github.com/josStorer/chatGPTBox/assets/13366013/3d05b2ee-10b2-4e04-b430-3b4610846fb9)
