### ISSUE TITLE
搜索引擎搜索的时候会慢半拍再出来

### ISSUE THREAD

**Issue by Darkslategray-lgtm** [ChatGPTBox-dev/chatGPTBox#42]
**Describe the bug**
**问题描述**
搜索引擎搜索的时候侧边chatGPT会慢半拍，答案再出来，而同类竞品 chatGPT-search-engine-extension 在这方面似乎没有这个问题。
同样使用OPENAI API GPT-3.5-turbo接口。

**Expected behavior**
**期望行为**
优化速度，达到与 chatGPT-search-engine-extension 同样的响应速度

**Comment by josStorer** [comment]
不是很确定你指的是不是我开发的[chatGPT-search-engine-extension](https://github.com/josStorer/chatGPT-search-engine-extension)
两者在这方面的工作原理完全一致, 我自己使用速度也没有问题
请问你使用的是什么搜索引擎, 你可以试试同时开启这两个扩展, 不排除是openai的服务器影响导致的偏差

**Comment by josStorer** [comment]
不是, 这个项目是该项目的原始上游, 其中多搜索引擎的支持是我开发的, 原理层面也是一样的

我注意到你的截图里, 我的插件生成的内容更长, 这方面有一定随机性, 生成内容更长等待也会更久

我建议你同时开启两个插件, 并都开启always模式, 然后测试5到10次, 对比速度

**Comment by josStorer** [comment]
主要是我这个支持了大量额外站点, 所以默认手动模式, 自动的可能很多站点不需要
