### ISSUE TITLE
被openAI检测并封号

### ISSUE THREAD

**Issue by SweetSalts** [ChatGPTBox-dev/chatGPTBox#54]
**Describe the bug**
使用这个插件会被openAI检测并封号。

账号已经被停用，使用API访问时被检测到“Common reasons for breach include violations of our usage policies or accessing the API from an unsupported location.”

**Screenshots**
**截图说明**
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/29419581/226565937-849d20d6-a1a0-4091-9ee0-edce8d211278.png">

**Comment by josStorer** [comment]
跟插件没关系，你可以直接在使用谷歌搜索关键词 chatgpt 封号 github 大量项目都有，因为你被检测了，你要是用机场请不要用api模式

**Comment by josStorer** [comment]
跟插件没关系，你可以直接在使用谷歌搜索关键词 chatgpt 封号 github 大量项目都有，因为你被检测了，你要是用机场请不要用api模式

例如: ![Screenshot_2023-03-21-18-41-25-389-edit_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/13366013/226582915-5fcfa1f7-1859-484b-b6fc-33629c4b8fd5.jpg)

**Comment by josStorer** [comment]
如果没有其他问题, 我先关闭了, 有其他问题随时评论

**Comment by tgzihg** [comment]
gg 我也被封了 刚看到这个issue
