### ISSUE TITLE
not available

### ISSUE THREAD

**Issue by zhl111** [ChatGPTBox-dev/chatGPTBox#571]
**Describe the bug**
**问题描述**
{"detail":"It is recommended to upgrade to the latest PandoraNext: [https://github.com/pandora-next/deploy"}](https://github.com/pandora-next/deploy%22%7D)

But，This URL opens with 404  

**Screenshots**
**截图说明**
![image](https://github.com/josStorer/chatGPTBox/assets/29135984/170a8f68-6bf7-40c8-8552-772fb7f93405)

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows] win64
 - Browser: [e.g. chrome, safari] chrome
 - Extension Version: [e.g. v2.0.2] 2.4.6

**Comment by josStorer** [comment]
Are you using a custom API URL?

**Comment by josStorer** [comment]
这地址似乎暂时未更新, 不是我维护的, 建议换回正常的地址

**Comment by josStorer** [comment]
https://chat.openai.com
