### ISSUE TITLE
Add Google Gemini API key supported

### ISSUE THREAD

**Issue by anuxs** [ChatGPTBox-dev/chatGPTBox#590]
**Is your feature request related to a problem? Please describe.**

Google Gemini API key is now available. After individuals apply for a free key, they can use it to implement many AIGC features. I hope it can be supported.

**Describe the solution you'd like**
add Google Gemini API key

**Additional context**
**其他**
NO

**Comment by PeterDaveHello** [comment]
Reference: https://ai.google.dev/docs/gemini_api_overview

**Comment by zuisong** [comment]
https://github.com/zuisong/gemini-openai-proxy

This might be useful. I'm already using it.

**Comment by PeterDaveHello** [comment]
BTW, they now have OpenAI compatible API at "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions", which will make the implementation easier, or at least, can be added as a custom model.

Reference:
- https://ai.google.dev/gemini-api/docs/openai
