### ISSUE TITLE
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by anuxs** [ChatGPTBox-dev/chatGPTBox#793]
**Describe the bug**
**问题描述**
When chromieu version is 130.X.X,the extension can't run but in chromieu 129.X.X no this problem
error:
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
无法正确加载扩展。它可能无法截获网络请求。

上下文
extension://ogepgejlhepmhijmgipeejjpgedbabbe/popup.html
堆栈跟踪
shared.js:2 (匿名函数)

**To Reproduce**
**如何复现**
on:
Microsoft Edge
版本 130.0.2849.5 (正式版本) stable应用，beta频道 (64 位)
click chatgptbox icon, report an error 

**Expected behavior**
**期望行为**
can run.

**Screenshots**
**截图说明**

**Please complete the following information):**
**请补全以下内容**
 - OS: [e.g. Windows]
 - Browser: Microsoft Edge 版本 130.0.2849.5 (正式版本) stable应用，beta频道 (64 位)
 - Extension Version: V 2.5.8

**Additional context**
**其他**

**Comment by josStorer** [comment]
点一下重新加载会好吗, 我这边129版本的chrome也出现了, 但是重新加载就好了
