### ISSUE TITLE
建议改进气泡设计，位置移动到选中内容上方，增加深色主题 | Suggestion to improve bubble design, move position above selected content, and add a dark theme.

### ISSUE THREAD

**Issue by kid101x** [ChatGPTBox-dev/chatGPTBox#82]
**Is your feature request related to a problem? Please describe.**
**新功能是否与解决某个问题相关, 请描述**

建议对交互进行改进。
当下版本选中内容后，气泡出现在鼠标正后方1个中文字符处，如果是句末，这不会有什么问题。但是选择句子中间的文字，并且如果像我一样从右往左选择内容，气泡会对视线造成了干扰。

**Describe the solution you'd like**
**你期望的新功能实现方案**

增加一个气泡位置移动到上方选项。
我个人觉得气泡显示在选中内容上一行或许会更好一些。

另外能不能给气泡加一个深色主题？

**Comment by josStorer** [comment]
我刚刚更新, 把位置移到了选中内容右下方, 因为很多手机上方是复制之类的菜单
https://github.com/josStorer/chatGPTBox/commit/ca32f8741413126686be737d1e66b7ede6f877e2

气泡深色主题容易看不清, 深色主题中一般小物件, 着重显示的文字等, 是亮色, 而气泡本身就是这个着重显示的东西, 所以我没做深色

**Comment by kid101x** [comment]
<details>> <summary>我刚刚更新, 把位置移到了选中内容右下方, 因为很多手机上方是复制之类的菜单</summary> [ca32f87](https://github.com/josStorer/chatGPTBox/commit/ca32f8741413126686be737d1e66b7ede6f877e2)
> 
> 气泡深色主题容易看不清, 深色主题中一般小物件, 着重显示的文字等, 是亮色, 而气泡本身就是这个着重显示的东西, 所以我没做深色
</details>
这两个考量是我没想到的。
使用中发现另一个设计，右键调用选项的窗口为什么没有图钉固定选项呢？

**Comment by josStorer** [comment]
邮件调用的窗口本身就是固定的, 不会消失, 因为我觉得当用户使用右键调出的, 这应该是一个刻意的, 强调性质的行为, 用户可能希望持续对话
